### ISSUE TITLE
Error: Module `Mouse` does not expose `Vector`

### ISSUE THREAD

**Issue by MiraiTunga** [r-k-b/sladial-rider#1]
Getting the following error when trying to run the project 

Module `Mouse` does not expose `Vector`

14| import Mouse exposing (Vector)

![capture](https://cloud.githubusercontent.com/assets/3772058/25229424/8770c656-2613-11e7-821a-075728e31d0d.PNG)

**Comment by r-k-b** [comment]
When I renamed 'Position' to 'Vector', phpstorm modified the `Mouse` module!

Fixed by a9d2d00d3a9876431c1db30e3fc776bfc2146a94 .
